
CREATE TABLE MPAS_GR_KHPJBZ (
       fabh                 INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       pjbh                 INTEGER NOT NULL,
       pjbzbh               INTEGER NOT NULL,
       pjlx                 VARCHAR(2),
       pjbz                 VARCHAR(200),
       bzf                  DECIMAL(25, 4),
       bzsm                 VARCHAR(1000),
       PRIMARY KEY (fabh, khzbdh, pjbh, pjbzbh)
);

CREATE UNIQUE INDEX XPKMPAS_GR_KHPJBZ ON MPAS_GR_KHPJBZ
(
       fabh                           ASC,
       khzbdh                         ASC,
       pjbh                           ASC,
       pjbzbh                         ASC
);


CREATE TABLE MPAS_GR_RWZX (
       rwbh                 INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       khdxdh               INTEGER NOT NULL,
       rwnr                 VARCHAR(100),
       rwdd                 VARCHAR(60),
       wcsj                 TIMESTAMP,
       rwsm                 VARCHAR(400),
       sfwc                 VARCHAR(2),
       czsj                 TIMESTAMP,
       lxdh                 VARCHAR(20),
       PRIMARY KEY (rwbh)
);

CREATE UNIQUE INDEX XPKMPAS_GR_RWZX ON MPAS_GR_RWZX
(
       rwbh                           ASC
);


CREATE TABLE MPAS_GR_YHFK (
       xh                   INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       dzyx                 VARCHAR(20),
       sjhm                 VARCHAR(20),
       yjfk                 VARCHAR(2000),
       txrq                 TIMESTAMP,
       PRIMARY KEY (xh)
);

CREATE UNIQUE INDEX XPKMPAS_GR_YHFK ON MPAS_GR_YHFK
(
       xh                             ASC
);


CREATE TABLE MPAS_GR_ZXPF (
       fabh                 INTEGER NOT NULL,
       khqs                 INTEGER NOT NULL,
       dfzkhdxdh            INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       xmbh                 INTEGER NOT NULL,
       khdx                 VARCHAR(2),
       wdmc                 VARCHAR(200),
       xmmc                 VARCHAR(100),
       khnr                 VARCHAR(2000),
       khzq                 INTEGER,
       xmdfsx               DECIMAL(25, 4),
       xmdfxx               DECIMAL(25, 4),
       df                   DECIMAL(25, 4),
       pfzt                 VARCHAR(2),
       khfamc               VARCHAR(100),
       pfksrq               INTEGER,
       pfjsrq               INTEGER,
       PRIMARY KEY (fabh, khqs, dfzkhdxdh, khdxdh, xmbh)
);

CREATE UNIQUE INDEX XPKMPAS_GR_ZXPF ON MPAS_GR_ZXPF
(
       fabh                           ASC,
       khqs                           ASC,
       dfzkhdxdh                      ASC,
       khdxdh                         ASC,
       xmbh                           ASC
);


CREATE TABLE MPAS_GR_ZXXX (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       xxbh                 INTEGER NOT NULL,
       xxlx                 VARCHAR2(2) NOT NULL,
       xxwd                 VARCHAR2(2) NOT NULL,
       xxzt                 VARCHAR2(80),
       xxnr                 VARCHAR2(2000),
       xxsj                 TIMESTAMP,
       sfck                 VARCHAR2(2),
       xxdz                 VARCHAR2(20),
       sfzy                 VARCHAR2(2),
       bxr                  VARCHAR2(12),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, xxbh, xxlx, xxwd)
);

CREATE UNIQUE INDEX XPKMPAS_GR_ZXXX ON MPAS_GR_ZXXX
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       xxbh                           ASC,
       xxlx                           ASC,
       xxwd                           ASC
);


CREATE TABLE MPAS_JX_JXGZ (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxlbdh               VARCHAR(8) NOT NULL,
       hymc                 VARCHAR(40) NOT NULL,
       jxlbmc               VARCHAR(40),
       jx                   DECIMAL(19, 2),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxlbdh)
);

CREATE UNIQUE INDEX XPKMPAS_JX_JXGZ ON MPAS_JX_JXGZ
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxlbdh                         ASC
);


CREATE TABLE MPAS_JX_JXGZ_LSSJ (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxlbdh               VARCHAR(8) NOT NULL,
       hymc                 VARCHAR(40) NOT NULL,
       jxlbmc               VARCHAR(40),
       jx                   DECIMAL(19, 2),
       PRIMARY KEY (tjrq, hykhdxdh, jxlbdh)
);

CREATE UNIQUE INDEX XPKMPAS_JX_JXGZ_LSSJ ON MPAS_JX_JXGZ_LSSJ
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       jxlbdh                         ASC
);


CREATE TABLE MPAS_JX_QHJXPHB (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxlbdh               INTEGER NOT NULL,
       jxlbmc               VARCHAR(40),
       jgmc                 VARCHAR(100),
       hymc                 VARCHAR(40),
       lbdh                 VARCHAR(10),
       lbmc                 VARCHAR(60),
       jx                   DECIMAL(19, 2),
       jxhz                 DECIMAL(19, 2),
       qhpm                 INTEGER,
       jgnpm                INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxlbdh)
);

CREATE UNIQUE INDEX XPKMPAS_JX_QHJXPHB ON MPAS_JX_QHJXPHB
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxlbdh                         ASC
);


CREATE TABLE MPAS_JX_QHJXPHB_LSSJ (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxlbdh               INTEGER NOT NULL,
       jxlbmc               VARCHAR(40),
       jgmc                 VARCHAR(100),
       hymc                 VARCHAR(40),
       lbdh                 VARCHAR(10),
       lbmc                 VARCHAR(60),
       jx                   DECIMAL(19, 2),
       jxhz                 DECIMAL(19, 2),
       qhpm                 INTEGER,
       jgnpm                INTEGER,
       PRIMARY KEY (tjrq, hykhdxdh, jxlbdh)
);

CREATE UNIQUE INDEX XPKMPAS_JX_QHJXPHB_LSSJ ON MPAS_JX_QHJXPHB_LSSJ
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       jxlbdh                         ASC
);


CREATE TABLE MPAS_JX_TDJXPHB (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jgmc                 VARCHAR(100),
       hymc                 VARCHAR(40),
       lbdh                 VARCHAR(10),
       lbmc                 VARCHAR(60),
       pm                   INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh)
);

CREATE UNIQUE INDEX XPKMPAS_JX_TDJXPHB ON MPAS_JX_TDJXPHB
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC
);


CREATE TABLE MPAS_JXBG_GZHZ (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       gwlbmc               VARCHAR(60),
       gzhz                 DECIMAL(19, 2),
       tgwpm                INTEGER,
       qhpm                 INTEGER,
       bsy                  DECIMAL(19, 2),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh)
);

CREATE UNIQUE INDEX XPKMPAS_JXBG_GZHZ ON MPAS_JXBG_GZHZ
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC
);


CREATE TABLE MPAS_JXBG_GZMX (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       gzxbh                VARCHAR(18) NOT NULL,
       gzxmc                VARCHAR(100),
       GZXZ                 DECIMAL(19, 2),
       pm                   INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, gzxbh)
);

CREATE UNIQUE INDEX XPKMPAS_JXBG_GZMX ON MPAS_JXBG_GZMX
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       gzxbh                          ASC
);


CREATE TABLE MPAS_JXBG_GZZC (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       gzlb                 VARCHAR(40) NOT NULL,
       gz                   DECIMAL(19, 2),
       gwlbmc               VARCHAR(100),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, gzlb)
);

CREATE UNIQUE INDEX XPKMPAS_JXBG_GZZC ON MPAS_JXBG_GZZC
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       gzlb                           ASC
);


CREATE TABLE MPAS_JXBG_KHQK (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khfl                 VARCHAR(200) NOT NULL,
       khh                  VARCHAR(100) NOT NULL,
       khmc                 VARCHAR(200),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, khfl, khh)
);

CREATE UNIQUE INDEX XPKMPAS_JXBG_KHQK ON MPAS_JXBG_KHQK
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       khfl                           ASC,
       khh                            ASC
);


CREATE TABLE MPAS_KH_BHKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       bhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_BHKH ON MPAS_KH_BHKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_BLDKDKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_BLDKDKH ON MPAS_KH_BLDKDKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_CKDKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_CKDKH ON MPAS_KH_CKDKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_CKDQKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       dqlx                 VARCHAR(20),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_CKDQKH ON MPAS_KH_CKDQKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_DKDKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_DKDKH ON MPAS_KH_DKDKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_DKDQKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       dqlx                 VARCHAR(20),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_DKDQKH ON MPAS_KH_DKDQKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_XZKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_XZKH ON MPAS_KH_XZKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_KH_YQDKDKH (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR(400),
       hyye                 DECIMAL(19, 2),
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_KH_YQDKDKH ON MPAS_KH_YQDKDKH
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_PAS_APPCDSZ (
       cdbh                 INTEGER NOT NULL,
       cdmc                 VARCHAR(50),
       cdms                 VARCHAR(100),
       cdtb                 VARCHAR(200),
       cddz                 VARCHAR(100),
       cdwd                 VARCHAR(20),
       PRIMARY KEY (cdbh)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_APPCDSZ ON MPAS_PAS_APPCDSZ
(
       cdbh                           ASC
);


CREATE TABLE MPAS_PAS_CDQSB (
       cdbh                 INTEGER NOT NULL,
       dybm                 VARCHAR(20) NOT NULL,
       bzwm                 VARCHAR(60),
       PRIMARY KEY (cdbh, dybm)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_CDQSB ON MPAS_PAS_CDQSB
(
       cdbh                           ASC,
       dybm                           ASC
);


CREATE TABLE MPAS_PAS_HYLBCDDZ (
       hylb                 VARCHAR(20) NOT NULL,
       cdbh                 INTEGER NOT NULL,
       cdwd                 VARCHAR(20),
       cdbm                 VARCHAR(50),
       cdms                 VARCHAR(100),
       px                   INTEGER,
       PRIMARY KEY (hylb, cdbh)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_HYLBCDDZ ON MPAS_PAS_HYLBCDDZ
(
       hylb                           ASC,
       cdbh                           ASC
);


CREATE TABLE MPAS_PAS_HYLBSJDZ (
       hylb                 VARCHAR(20) NOT NULL,
       cdbh                 INTEGER NOT NULL,
       dybm                 VARCHAR(20) NOT NULL,
       cdqssql              VARCHAR(4000),
       sjfw                 VARCHAR(2),
       khzq                 VARCHAR(1),
       famc                 VARCHAR(100),
       PRIMARY KEY (hylb, cdbh, dybm)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_HYLBSJDZ ON MPAS_PAS_HYLBSJDZ
(
       hylb                           ASC,
       cdbh                           ASC,
       dybm                           ASC
);


CREATE TABLE MPAS_PAS_HYLBSJSX (
       hylb                 VARCHAR(20) NOT NULL,
       cdbh                 INTEGER NOT NULL,
       dybm                 VARCHAR(20) NOT NULL,
       sxmc                 VARCHAR(20) NOT NULL,
       sxz                  VARCHAR(4000),
       PRIMARY KEY (hylb, cdbh, dybm, sxmc)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_HYLBSJSX ON MPAS_PAS_HYLBSJSX
(
       hylb                           ASC,
       cdbh                           ASC,
       dybm                           ASC,
       sxmc                           ASC
);


CREATE TABLE MPAS_PAS_HZKHZB (
       khzbdh               INTEGER NOT NULL,
       khlx                 VARCHAR(2) NOT NULL,
       KHZBMC               VARCHAR(200) NOT NULL,
       zbmc                 VARCHAR(200),
       zbdh                 INTEGER,
       sdbs                 VARCHAR(20),
       tjkj                 VARCHAR(20),
       bz                   VARCHAR(20),
       PRIMARY KEY (khzbdh, khlx)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_HZKHZB ON MPAS_PAS_HZKHZB
(
       khzbdh                         ASC,
       khlx                           ASC
);


CREATE TABLE MPAS_PAS_KHZB (
       hylb                 VARCHAR(20) NOT NULL,
       cdbh                 INTEGER NOT NULL,
       dybm                 VARCHAR(20) NOT NULL,
       khzbdh               INTEGER NOT NULL,
       px                   INTEGER,
       PRIMARY KEY (hylb, cdbh, dybm, khzbdh)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_KHZB ON MPAS_PAS_KHZB
(
       hylb                           ASC,
       cdbh                           ASC,
       dybm                           ASC,
       khzbdh                         ASC
);


CREATE TABLE MPAS_PAS_SJYSXSZ (
       bm                   VARCHAR(20) NOT NULL,
       sxmc                 VARCHAR(10) NOT NULL,
       zwmc                 VARCHAR(20),
       sfbt                 VARCHAR(6),
       sjlx                 VARCHAR(20),
       mrz                  VARCHAR(10),
       bjlx                 VARCHAR(20),
       xsfs                 VARCHAR(20),
       sfqx                 VARCHAR(6),
       zy                   VARCHAR(800),
       PRIMARY KEY (bm, sxmc)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_SJYSXSZ ON MPAS_PAS_SJYSXSZ
(
       bm                             ASC,
       sxmc                           ASC
);


CREATE TABLE MPAS_PAS_SJYSZ (
       bm                   VARCHAR(20) NOT NULL,
       bzwm                 VARCHAR(60),
       zjzd                 VARCHAR(200),
       qssql                VARCHAR(4000),
       PRIMARY KEY (bm)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_SJYSZ ON MPAS_PAS_SJYSZ
(
       bm                             ASC
);


CREATE TABLE MPAS_PAS_XTXX (
       xxbh                 INTEGER NOT NULL,
       hydh                 VARCHAR(12),
       hymc                 VARCHAR(40),
       xxzt                 VARCHAR(800),
       xxnr                 VARCHAR(4000),
       xxsj                 TIMESTAMP,
       tshylb               VARCHAR(200) NOT NULL,
       tshylbmc             VARCHAR(2000),
       tszt                 CHAR(1),
       sfzy                 VARCHAR(2),
       PRIMARY KEY (xxbh)
);

CREATE UNIQUE INDEX XPKMPAS_PAS_XTXX ON MPAS_PAS_XTXX
(
       xxbh                           ASC
);


CREATE TABLE MPAS_SZ_CZRZ (
       bh                   INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       tjrq                 INTEGER NOT NULL,
       dlkhdxdh             INTEGER NOT NULL,
       cdbh                 INTEGER,
       czsj                 TIMESTAMP,
       cdmc                 VARCHAR(100),
       sfscdl               INTEGER,
       PRIMARY KEY (bh)
);

CREATE UNIQUE INDEX XPKMPAS_SZ_CZRZ ON MPAS_SZ_CZRZ
(
       bh                             ASC
);


CREATE TABLE MPAS_SZ_GRCSSZ (
       khdxdh               INTEGER NOT NULL,
       cslx                 VARCHAR(2) NOT NULL,
       csz                  VARCHAR(10),
       sfqy                 VARCHAR(2),
       PRIMARY KEY (khdxdh, cslx)
);

CREATE UNIQUE INDEX XPKMPAS_SZ_GRCSSZ ON MPAS_SZ_GRCSSZ
(
       khdxdh                         ASC,
       cslx                           ASC
);


CREATE TABLE MPAS_SZ_GRGZKH (
       khdxdh               INTEGER NOT NULL,
       khh                  VARCHAR(30) NOT NULL,
       khmc                 VARCHAR(100),
       gzsj                 TIMESTAMP,
       gzzt                 VARCHAR(2),
       PRIMARY KEY (khdxdh, khh)
);

CREATE UNIQUE INDEX XPKMPAS_SZ_GRGZKH ON MPAS_SZ_GRGZKH
(
       khdxdh                         ASC,
       khh                            ASC
);


CREATE TABLE MPAS_SZ_XTCSSZ (
       csmc                 VARCHAR(40) NOT NULL,
       csz                  VARCHAR(200),
       csms                 VARCHAR(100),
       PRIMARY KEY (csmc)
);

CREATE UNIQUE INDEX XPKMPAS_SZ_XTCSSZ ON MPAS_SZ_XTCSSZ
(
       csmc                           ASC
);


CREATE TABLE MPAS_SZ_XXTS (
       bh                   INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       xxlx                 VARCHAR(8),
       xxlj                 VARCHAR(60),
       tsnr                 VARCHAR(2000),
       tssj                 TIMESTAMP,
       tshy                 INTEGER,
       zt                   VARCHAR(2),
       PRIMARY KEY (bh)
);

CREATE UNIQUE INDEX XPKMPAS_SZ_XXTS ON MPAS_SZ_XXTS
(
       bh                             ASC
);


CREATE TABLE MPAS_XT_CKZH (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       hyye                 DECIMAL(25, 4),
       ghxx                 VARCHAR(400),
       gxhslx               VARCHAR(1),
       ghqsrq               INTEGER,
       ghjsrq               INTEGER,
       hykhye               DECIMAL(19, 2),
       pm                   INTEGER,
       jldqts               INTEGER,
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, hykhdxdh, jxdxdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_CKZH ON MPAS_XT_CKZH
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC
);


CREATE TABLE MPAS_XT_DKZH (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       zhdh                 VARCHAR(40) NOT NULL,
       zhbs                 VARCHAR(2),
       kmh                  VARCHAR(20),
       kmmc                 VARCHAR(40),
       khh                  VARCHAR(30),
       khmc                 VARCHAR(100),
       khrq                 INTEGER,
       dqrq                 INTEGER,
       jgdh                 VARCHAR(20),
       khjgmc               VARCHAR(100),
       zhye                 DECIMAL(19, 2),
       hyye                 DECIMAL(25, 4),
       ghxx                 VARCHAR(400),
       gxhslx               VARCHAR(1),
       ghqsrq               INTEGER,
       ghjsrq               INTEGER,
       hykhye               DECIMAL(19, 2),
       pm                   INTEGER,
       wjfl                 VARCHAR(2),
       jldqts               INTEGER,
       bz                   VARCHAR(3),
       PRIMARY KEY (tjrq, hykhdxdh, jxdxdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_DKZH ON MPAS_XT_DKZH
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       jxdxdh                         ASC
);


CREATE TABLE MPAS_XT_DLRCKHYQX (
       dlkhdxdh             INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       jsdh                 INTEGER NOT NULL,
       dqjsbz               INTEGER,
       hydh                 VARCHAR(12),
       hymc                 VARCHAR(100),
       PRIMARY KEY (dlkhdxdh, khdxdh, jsdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_DLRCKHYQX ON MPAS_XT_DLRCKHYQX
(
       dlkhdxdh                       ASC,
       khdxdh                         ASC,
       jsdh                           ASC
);


CREATE TABLE MPAS_XT_DLRCKJGQX (
       dlkhdxdh             INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       jsdh                 INTEGER NOT NULL,
       dqjsbz               INTEGER,
       jgdh                 VARCHAR(10),
       jgmc                 VARCHAR(100),
       ckhybz               VARCHAR(1),
       PRIMARY KEY (dlkhdxdh, khdxdh, jsdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_DLRCKJGQX ON MPAS_XT_DLRCKJGQX
(
       dlkhdxdh                       ASC,
       khdxdh                         ASC,
       jsdh                           ASC
);


CREATE TABLE MPAS_XT_GZKH (
       tjrq                 INTEGER NOT NULL,
       jxdxdh               INTEGER NOT NULL,
       jxdxlx               INTEGER NOT NULL,
       zhdh                 VARCHAR2(40) NOT NULL,
       kmh                  VARCHAR2(20),
       kmmc                 VARCHAR2(40),
       khh                  VARCHAR2(30),
       khmc                 VARCHAR2(100),
       khrq                 INTEGER,
       jgdh                 VARCHAR2(20),
       khjgmc               VARCHAR2(100),
       dqrq                 INTEGER,
       zhye                 DECIMAL(19, 2),
       ghxx                 VARCHAR2(400),
       hyye                 DECIMAL(19, 2),
       PRIMARY KEY (tjrq, jxdxdh, jxdxlx)
);

CREATE UNIQUE INDEX XPKMPAS_XT_GZKH ON MPAS_XT_GZKH
(
       tjrq                           ASC,
       jxdxdh                         ASC,
       jxdxlx                         ASC
);


CREATE TABLE MPAS_XT_HY (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       lbdh                 VARCHAR(10) NOT NULL,
       hydh                 VARCHAR(12) NOT NULL,
       hymc                 VARCHAR(40),
       jgkhdxdh             INTEGER,
       jgdh                 VARCHAR(20),
       jgmc                 VARCHAR(100),
       lbmc                 VARCHAR(60),
       dlmc                 VARCHAR(12),
       dlmm                 VARCHAR(32),
       xb                   VARCHAR(2),
       PRIMARY KEY (tjrq, khdxdh, lbdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_HY ON MPAS_XT_HY
(
       tjrq                           ASC,
       khdxdh                         ASC,
       lbdh                           ASC
);


CREATE TABLE MPAS_XT_HYDYCD (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       cdbh                 INTEGER NOT NULL,
       lbdh                 VARCHAR(10) NOT NULL,
       cdmc                 VARCHAR(20),
       cdms                 VARCHAR(100),
       cddz                 VARCHAR(100),
       cdwd                 VARCHAR(2),
       cdtb                 VARCHAR(200),
       cdpx                 INTEGER,
       PRIMARY KEY (tjrq, khdxdh, cdbh, lbdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_HYDYCD ON MPAS_XT_HYDYCD
(
       tjrq                           ASC,
       khdxdh                         ASC,
       cdbh                           ASC,
       lbdh                           ASC
);


CREATE TABLE MPAS_XT_HYJH (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzq                 VARCHAR(1) NOT NULL,
       jhz                  DECIMAL(19, 2),
       lzz                  DECIMAL(19, 2),
       PRIMARY KEY (tjrq, hykhdxdh, khzbdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_XT_HYJH ON MPAS_XT_HYJH
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_XT_HYYJ (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       ywlb                 VARCHAR(2),
       hydh                 VARCHAR(12),
       hymc                 VARCHAR(100),
       xnhybz               VARCHAR(1),
       PRIMARY KEY (tjrq, hykhdxdh, khzbdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_HYYJ ON MPAS_XT_HYYJ
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC
);


CREATE TABLE MPAS_XT_JGJH (
       tjrq                 INTEGER NOT NULL,
       jgkhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzq                 VARCHAR(1) NOT NULL,
       jhz                  DECIMAL(19, 2),
       lzz                  DECIMAL(19, 2),
       PRIMARY KEY (tjrq, jgkhdxdh, khzbdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_XT_JGJH ON MPAS_XT_JGJH
(
       tjrq                           ASC,
       jgkhdxdh                       ASC,
       khzbdh                         ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_XT_JGYJ (
       tjrq                 INTEGER NOT NULL,
       jgkhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       ywlb                 VARCHAR(2),
       jgdh                 VARCHAR(10),
       jgmc                 VARCHAR(100),
       PRIMARY KEY (tjrq, jgkhdxdh, khzbdh)
);

CREATE UNIQUE INDEX XPKMPAS_XT_JGYJ ON MPAS_XT_JGYJ
(
       tjrq                           ASC,
       jgkhdxdh                       ASC,
       khzbdh                         ASC
);


CREATE TABLE MPAS_XX_HF (
       hfbh                 INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       plbh                 INTEGER NOT NULL,
       hf                   VARCHAR(2000),
       czsj                 TIMESTAMP,
       PRIMARY KEY (hfbh)
);

CREATE UNIQUE INDEX XPKMPAS_XX_HF ON MPAS_XX_HF
(
       hfbh                           ASC
);


CREATE TABLE MPAS_XX_PL (
       plbh                 INTEGER NOT NULL GENERATED BY DEFAULT 
				AS IDENTITY( 
					START WITH 1,
					INCREMENT BY 1,
					CACHE 20,
					NO CYCLE ),
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       cdbh                 INTEGER NOT NULL,
       pl                   VARCHAR(2000),
       czsj                 TIMESTAMP,
       PRIMARY KEY (plbh)
);

CREATE UNIQUE INDEX XPKMPAS_XX_PL ON MPAS_XX_PL
(
       plbh                           ASC
);


CREATE TABLE MPAS_XX_Z (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       cdbh                 INTEGER NOT NULL,
       czsj                 TIMESTAMP,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, cdbh)
);

CREATE UNIQUE INDEX XPKMPAS_XX_Z ON MPAS_XX_Z
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       cdbh                           ASC
);


CREATE TABLE MPAS_YJ_GRYJ (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzq                 VARCHAR(20) NOT NULL,
       ywlb                 VARCHAR(2),
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       jhz                  DECIMAL(19, 2),
       df                   DECIMAL(19, 2),
       jgnpm                INTEGER,
       qhpm                 INTEGER,
       px                   INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, khzbdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_YJ_GRYJ ON MPAS_YJ_GRYJ
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_YJ_GRYJ_LSSJ (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       khzq                 VARCHAR(20) NOT NULL,
       ywlb                 VARCHAR(2),
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       jhz                  DECIMAL(19, 2),
       df                   DECIMAL(19, 2),
       jgnpm                INTEGER,
       qhpm                 INTEGER,
       px                   INTEGER,
       PRIMARY KEY (tjrq, hykhdxdh, khzbdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_YJ_GRYJ_LSSJ ON MPAS_YJ_GRYJ_LSSJ
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_YJ_JGYJ (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       jgkhdxdh             INTEGER NOT NULL,
       khzq                 VARCHAR(1) NOT NULL,
       ywlb                 VARCHAR(2),
       jgdh                 VARCHAR(10),
       jgmc                 VARCHAR(100),
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       jhz                  DECIMAL(19, 2),
       df                   DECIMAL(19, 2),
       qhpm                 INTEGER,
       px                   INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, khzbdh, jgkhdxdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_YJ_JGYJ ON MPAS_YJ_JGYJ
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       jgkhdxdh                       ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_YJ_JGYJ_LSSJ (
       tjrq                 INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       jgkhdxdh             INTEGER NOT NULL,
       khzq                 VARCHAR(1) NOT NULL,
       ywlb                 VARCHAR(2),
       jgdh                 VARCHAR(10),
       jgmc                 VARCHAR(100),
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       jhz                  DECIMAL(19, 2),
       df                   DECIMAL(19, 2),
       qhpm                 INTEGER,
       px                   INTEGER,
       PRIMARY KEY (tjrq, hykhdxdh, khzbdh, jgkhdxdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_YJ_JGYJ_LSSJ ON MPAS_YJ_JGYJ_LSSJ
(
       tjrq                           ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       jgkhdxdh                       ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_YJ_QHYJ (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       khzbdh               INTEGER NOT NULL,
       jgkhdxdh             INTEGER NOT NULL,
       khzq                 VARCHAR(1) NOT NULL,
       ywlb                 VARCHAR(2),
       jgdh                 VARCHAR(10),
       jgmc                 VARCHAR(100),
       khzbmc               VARCHAR(100),
       khzbz                DECIMAL(19, 2),
       jhz                  DECIMAL(19, 2),
       df                   DECIMAL(19, 2),
       qhpm                 INTEGER,
       px                   INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, khzbdh, jgkhdxdh, khzq)
);

CREATE UNIQUE INDEX XPKMPAS_YJ_QHYJ ON MPAS_YJ_QHYJ
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       khzbdh                         ASC,
       jgkhdxdh                       ASC,
       khzq                           ASC
);


CREATE TABLE MPAS_ZDWD_WD (
       tjrq                 INTEGER NOT NULL,
       khdxdh               INTEGER NOT NULL,
       hykhdxdh             INTEGER NOT NULL,
       wdbh                 INTEGER NOT NULL,
       wdmc                 VARCHAR(200),
       scr                  INTEGER,
       scrq                 INTEGER,
       pxbz                 INTEGER,
       PRIMARY KEY (tjrq, khdxdh, hykhdxdh, wdbh)
);

CREATE UNIQUE INDEX XPKMPAS_ZDWD_WD ON MPAS_ZDWD_WD
(
       tjrq                           ASC,
       khdxdh                         ASC,
       hykhdxdh                       ASC,
       wdbh                           ASC
);


CREATE TABLE tmp_wheresql (
       菜单编号             INTEGER,
       对应表名             VARCHAR(20),
       数据范围             VARCHAR(2),
       菜单取数sql          VARCHAR(2000),
       行员类别值           VARCHAR(800),
       考核周期             VARCHAR(2000)
);



